// harness: run one function variant of the Harvest executable on generated inputs and print what it did.
//
// Usage: harness IMAGE VARIANT ENTRY ARGSPEC SEED COUNT
//
// IMAGE is the original executable, whose PT_LOAD segments are mapped at their fixed addresses: the
// read-only segment as it is in the file, without execute permission, and the writable segment with its
// file contents followed by generated bytes where the file has none (.bss). VARIANT is a fixed-address
// executable holding the function under test, linked by oracle.py at 0x20000000; ENTRY is the function's
// address in it. ARGSPEC gives the function's arguments in order: p (pointer), i (integer), b (bool),
// f (float) and d (double).
//
// Memory the function reaches through generated pointers lies in a region that is mapped on first touch,
// one page at a time, with bytes that depend only on the case seed and the address, so every variant
// reads the same memory whatever order it reads it in. A call that lands in the region or in the image's
// code is recorded as a call out of the function (target address and argument registers) and returns a
// generated value; so is a call to a named stub, which oracle.py generates for callees without a known
// address. Each case runs in a forked child. The parent prints one JSON line per case: the outcome, the
// return registers, the calls in order and every byte written to the region or to the image.
#define _GNU_SOURCE
#include <elf.h>
#include <fcntl.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <ucontext.h>
#include <unistd.h>
#include <math.h>

#define PAGE 4096UL
#define REGION_BASE 0x100000000000UL
#define REGION_SIZE 0x010000000000UL
#define MAX_PAGES 8192
#define MAX_CALLS 4096
#define MAX_SEGMENTS 8
#define STACK_BASE 0x30000000UL
#define STACK_SIZE 0x100000UL

struct regs {
  uint64_t gp[6];   // rdi, rsi, rdx, rcx, r8, r9
  uint64_t xmm[8];  // low 64 bits of xmm0..xmm7
  uint64_t rax;     // al carries the vector register count for variadic callees
};

struct result {
  uint64_t rax, rdx, xmm0, xmm1;
};

struct call {
  uint64_t target;    // address called, or 0 for a named stub
  const char *name;   // named stub, else NULL
  struct regs regs;
  unsigned char deref[6][32];  // what each argument register points at, when it points into the stack or the variant
};

struct segment {
  uint64_t start, end;  // page-aligned
  int writable;
  unsigned char *pristine;  // writable segments: contents before the case
};

static struct segment image[MAX_SEGMENTS], variant[MAX_SEGMENTS];
static int image_count, variant_count;
static uint64_t image_text_start, image_text_end;

static uint64_t seed;
static uint64_t pages[MAX_PAGES];
static int page_count;
static struct call calls[MAX_CALLS];
static int call_count;
static uint64_t return_counter;
static int out_fd;

// splitmix64
static uint64_t mix(uint64_t x) {
  x += 0x9e3779b97f4a7c15UL;
  x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9UL;
  x = (x ^ (x >> 27)) * 0x94d049bb133111ebUL;
  return x ^ (x >> 31);
}

static const uint32_t floats[] = {
  0x00000000, 0x80000000, 0x3f800000, 0xbf800000, 0x3f000000, 0x41200000, 0x42c80000, 0xc2c80000,
  0x7f800000, 0xff800000, 0x7fc00000, 0xffc00000, 0x00000001, 0x7f7fffff, 0x3dcccccd, 0x447a0000,
};
static const uint64_t doubles[] = {
  0x0000000000000000UL, 0x3ff0000000000000UL, 0xbff0000000000000UL, 0x3fe0000000000000UL,
  0x7ff0000000000000UL, 0xfff0000000000000UL, 0x7ff8000000000000UL, 0x4059000000000000UL,
};

// 16-byte aligned float bit patterns, special values included.
static const uint32_t aligned_floats[] = {
  0x00000000, 0x80000000, 0x3f800000, 0xbf800000, 0x3f000000, 0x41200000, 0x42c80000, 0xc2c80000,
  0x7f800000, 0xff800000, 0x7fc00000, 0xffc00000, 0x447a0000, 0x7fc00000, 0x7f800000, 0xff800000,
};

// A pointer into the region's lower half. Half of them carry a float bit pattern in their low 32 bits, so a
// float field read from memory filled with pointers still sees NaN, the infinities and ordinary values.
static uint64_t region_pointer(uint64_t h) {
  uint64_t high = ((h >> 12) % (REGION_SIZE / 2 >> 32)) << 32;
  uint64_t low = (h >> 40) & 1 ? aligned_floats[(h >> 44) & 15] : (h >> 4) & 0xfffffff0UL;
  return REGION_BASE + high + low;
}

// The generated value of a word: pointers into the region most often, then small integers, zero,
// float and double bit patterns (NaN and the infinities included) and arbitrary words.
static uint64_t word(uint64_t h) {
  // Three seeds in four follow pointers: pointers and zero (which ends lists and trees) only.
  if (seed & 3) {
    if ((h & 15) < 13)
      return region_pointer(h);
    return (h & 15) == 15 ? 1 : 0;
  }
  switch (h & 15) {
  case 0: case 1: case 2: case 3: case 4: case 5: case 6: case 7: case 8:
    return region_pointer(h);
  case 9: case 10: return (h >> 8) & 0xff;
  case 11: return 0;
  case 12: return ((uint64_t)floats[(h >> 8) & 15] << 32) | floats[(h >> 12) & 15];
  case 13: return doubles[(h >> 8) & 7];
  case 14: return 1;
  default: return h;
  }
}

static uint64_t word_at(uint64_t address) { return word(mix(seed ^ mix(address))); }

static void fill(uint64_t page, unsigned char *to) {
  for (uint64_t offset = 0; offset < PAGE; offset += 8) {
    uint64_t w = word_at(page + offset);
    memcpy(to + offset, &w, 8);
  }
}

static void emit(const char *text) {
  size_t n = strlen(text);
  while (n > 0) {
    ssize_t w = write(out_fd, text, n);
    if (w <= 0)
      _exit(3);
    text += w;
    n -= w;
  }
}

static void finish(const char *outcome, uint64_t detail, const struct result *result);
static size_t hex(char *to, const unsigned char *from, size_t n);

static int map_region_page(uint64_t address) {
  uint64_t page = address & ~(PAGE - 1);
  if (page_count == MAX_PAGES)
    return 0;
  void *p = mmap((void *)page, PAGE, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED_NOREPLACE, -1, 0);
  if (p != (void *)page)
    return 0;
  fill(page, p);
  pages[page_count++] = page;
  return 1;
}

static int in_region(uint64_t a) { return a >= REGION_BASE && a < REGION_BASE + REGION_SIZE; }

// Addresses whose value differs between variants for the same behavior: the function's stack frame and the
// variant's own data. Arguments pointing there are compared by the bytes they point at.
static int local(uint64_t a) {
  if (a >= STACK_BASE && a + 32 <= STACK_BASE + STACK_SIZE)
    return 1;
  for (int i = 0; i < variant_count; i++)
    if (a >= variant[i].start && a + 32 <= variant[i].end)
      return 1;
  // The image's read-only data too: one variant may pass its own copy of a string the other takes from there.
  for (int i = 0; i < image_count; i++)
    if (!image[i].writable && a >= image[i].start && a + 32 <= image[i].end)
      return 1;
  return 0;
}

static void return_values(struct result *r) {
  uint64_t h = mix(seed ^ mix(0x5eed0000UL + return_counter++));
  r->rax = word(h);
  r->rdx = word(mix(h));
  r->xmm0 = ((h >> 20) & 1) ? doubles[(h >> 21) & 7] : floats[(h >> 21) & 15];
  r->xmm1 = 0;
}

static void record(uint64_t target, const char *name, const struct regs *regs) {
  if (call_count == MAX_CALLS)
    finish("too-many-calls", 0, NULL);
  calls[call_count].target = target;
  calls[call_count].name = name;
  calls[call_count].regs = *regs;
  memset(calls[call_count].deref, 0, sizeof(calls[call_count].deref));
  for (int i = 0; i < 6; i++)
    if (local(regs->gp[i]))
      memcpy(calls[call_count].deref[i], (void *)regs->gp[i], 32);
  call_count++;
}

// Called by oracle_thunk for named stubs.
// Allocators return fresh memory: a region pointer of their own, which no generated word points into.
static const char *allocators[] = { "_Znwm", "_Znam", "malloc", "calloc", "realloc", NULL };

// Math library functions have no side effects, so a compiler may reorder or combine their calls (sin and
// cos into sincos). They run for real and are not recorded, so they neither appear in the call order nor
// shift the generated return values of later calls.
static int math(const char *name, const struct regs *regs, struct result *r) {
  double d0, d1;
  float f0, f1;
  memcpy(&d0, &regs->xmm[0], 8);
  memcpy(&d1, &regs->xmm[1], 8);
  memcpy(&f0, &regs->xmm[0], 4);
  memcpy(&f1, &regs->xmm[1], 4);
  double d = 0;
  float f = 0;
  int single = 0;
#define D1(n) if (strcmp(name, #n) == 0) d = n(d0); else
#define F1(n) if (strcmp(name, #n) == 0) f = n(f0), single = 1; else
  D1(sin) D1(cos) D1(tan) D1(asin) D1(acos) D1(atan) D1(sqrt) D1(exp) D1(log) D1(log10) D1(floor) D1(ceil) D1(fabs)
  F1(sinf) F1(cosf) F1(tanf) F1(asinf) F1(acosf) F1(atanf) F1(sqrtf) F1(expf) F1(logf) F1(log10f) F1(floorf)
  F1(ceilf) F1(fabsf)
  if (strcmp(name, "atan2") == 0) d = atan2(d0, d1);
  else if (strcmp(name, "pow") == 0) d = pow(d0, d1);
  else if (strcmp(name, "fmod") == 0) d = fmod(d0, d1);
  else if (strcmp(name, "atan2f") == 0) f = atan2f(f0, f1), single = 1;
  else if (strcmp(name, "powf") == 0) f = powf(f0, f1), single = 1;
  else if (strcmp(name, "fmodf") == 0) f = fmodf(f0, f1), single = 1;
  else if (strcmp(name, "sincos") == 0) {
    sincos(d0, (double *)regs->gp[0], (double *)regs->gp[1]);
    return 1;
  } else if (strcmp(name, "sincosf") == 0) {
    sincosf(f0, (float *)regs->gp[0], (float *)regs->gp[1]);
    return 1;
  } else
    return 0;
#undef D1
#undef F1
  r->xmm0 = 0;
  if (single)
    memcpy(&r->xmm0, &f, 4);
  else
    memcpy(&r->xmm0, &d, 8);
  return 1;
}

void oracle_stub(const char *name, const struct regs *regs, struct result *r) {
  memset(r, 0, sizeof(*r));
  if (math(name, regs, r))
    return;
  record(0, name, regs);
  return_values(r);
  for (const char **a = allocators; *a; a++)
    if (strcmp(name, *a) == 0)
      r->rax = REGION_BASE + REGION_SIZE / 2 + (uint64_t)call_count * 0x100000;
}

static void handler(int signal, siginfo_t *info, void *context) {
  ucontext_t *uc = context;
  greg_t *g = uc->uc_mcontext.gregs;
  uint64_t rip = g[REG_RIP], fault = (uint64_t)info->si_addr;
  if (signal == SIGALRM)
    finish("timeout", rip, NULL);
  if (signal == SIGSEGV) {
    // A call into the region or into the image's code: record it and return a generated value.
    if (fault == rip && (in_region(rip) || (rip >= image_text_start && rip < image_text_end))) {
      struct regs regs = { { g[REG_RDI], g[REG_RSI], g[REG_RDX], g[REG_RCX], g[REG_R8], g[REG_R9] } };
      for (int i = 0; i < 8; i++)
        memcpy(&regs.xmm[i], &uc->uc_mcontext.fpregs->_xmm[i], 8);
      regs.rax = g[REG_RAX];
      record(rip, NULL, &regs);
      struct result r;
      return_values(&r);
      g[REG_RAX] = r.rax;
      g[REG_RDX] = r.rdx;
      memcpy(&uc->uc_mcontext.fpregs->_xmm[0], &r.xmm0, 8);
      memcpy(&uc->uc_mcontext.fpregs->_xmm[1], &r.xmm1, 8);
      uint64_t *sp = (uint64_t *)g[REG_RSP];
      g[REG_RIP] = sp[0];
      g[REG_RSP] += 8;
      return;
    }
    if (in_region(fault) && map_region_page(fault))
      return;
    finish("crash", fault, NULL);
  }
  finish(signal == SIGFPE ? "fpe" : signal == SIGILL ? "ill" : signal == SIGBUS ? "bus" : "signal", rip, NULL);
}

static char line[1 << 22];

static size_t hex(char *to, const unsigned char *from, size_t n) {
  static const char digits[] = "0123456789abcdef";
  for (size_t i = 0; i < n; i++) {
    to[2 * i] = digits[from[i] >> 4];
    to[2 * i + 1] = digits[from[i] & 15];
  }
  return 2 * n;
}

// Append the written byte runs of [start, end) against its original contents.
static size_t writes(char *to, size_t used, uint64_t start, const unsigned char *now, const unsigned char *before, size_t n,
                     int *first) {
  size_t i = 0;
  while (i < n && used < sizeof(line) - 256) {
    if (now[i] == before[i]) {
      i++;
      continue;
    }
    // Whole aligned words, so that a pointer stored over bytes that already matched still appears whole.
    i &= ~(size_t)7;
    size_t j = i;
    while (j < n && j - i < 4096) {
      size_t w = n - j < 8 ? n - j : 8;
      if (memcmp(now + j, before + j, w) == 0)
        break;
      j += w;
    }
    if (used + 64 + 2 * (j - i) >= sizeof(line))
      break;
    used += sprintf(to + used, "%s[\"0x%lx\",\"", *first ? "" : ",", start + i);
    used += hex(to + used, now + i, j - i);
    used += sprintf(to + used, "\"]");
    *first = 0;
    i = j;
  }
  return used;
}

static void finish(const char *outcome, uint64_t detail, const struct result *result) {
  size_t n = sprintf(line, "{\"seed\":%lu,\"outcome\":\"%s\",\"detail\":\"0x%lx\"", seed, outcome, detail);
  if (result)
    n += sprintf(line + n, ",\"rax\":\"0x%lx\",\"rdx\":\"0x%lx\",\"xmm0\":\"0x%lx\",\"xmm1\":\"0x%lx\"", result->rax,
                 result->rdx, result->xmm0, result->xmm1);
  n += sprintf(line + n, ",\"calls\":[");
  for (int i = 0; i < call_count && n < sizeof(line) - 1024; i++) {
    struct call *c = &calls[i];
    n += sprintf(line + n, "%s{\"to\":\"%s%s0x%lx\",\"gp\":[", i ? "," : "", c->name ? c->name : "", c->name ? "@" : "",
                 c->target);
    for (int r = 0; r < 6; r++)
      n += sprintf(line + n, "%s\"0x%lx\"", r ? "," : "", c->regs.gp[r]);
    n += sprintf(line + n, "],\"deref\":[");
    for (int r = 0; r < 6; r++) {
      n += sprintf(line + n, "%s\"", r ? "," : "");
      if (local(c->regs.gp[r]))
        n += hex(line + n, c->deref[r], 32);
      n += sprintf(line + n, "\"");
    }
    n += sprintf(line + n, "],\"xmm\":[");
    for (int r = 0; r < 8; r++)
      n += sprintf(line + n, "%s\"0x%lx\"", r ? "," : "", c->regs.xmm[r]);
    n += sprintf(line + n, "]}");
  }
  n += sprintf(line + n, "],\"writes\":[");
  int first = 1;
  static unsigned char before[PAGE];
  for (int i = 0; i < page_count; i++) {
    fill(pages[i], before);
    n = writes(line, n, pages[i], (unsigned char *)pages[i], before, PAGE, &first);
  }
  for (int i = 0; i < image_count; i++)
    if (image[i].writable)
      n = writes(line, n, image[i].start, (unsigned char *)image[i].start, image[i].pristine, image[i].end - image[i].start,
                 &first);
  n += sprintf(line + n, "],\"pages\":%d}\n", page_count);
  emit(line);
  _exit(0);
}

// Map the PT_LOAD segments of an executable at their addresses. Image segments are kept without execute
// permission so that calls into them fault and are recorded; variant segments are mapped as linked.
static int map_elf(const char *path, struct segment *segments, int *count, int is_image, uint64_t *text_start,
                   uint64_t *text_end) {
  int fd = open(path, O_RDONLY);
  if (fd < 0)
    return perror(path), 0;
  struct stat st;
  fstat(fd, &st);
  unsigned char *file = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
  Elf64_Ehdr *eh = (Elf64_Ehdr *)file;
  Elf64_Phdr *ph = (Elf64_Phdr *)(file + eh->e_phoff);
  for (int i = 0; i < eh->e_phnum; i++) {
    if (ph[i].p_type != PT_LOAD)
      continue;
    uint64_t start = ph[i].p_vaddr & ~(PAGE - 1), end = (ph[i].p_vaddr + ph[i].p_memsz + PAGE - 1) & ~(PAGE - 1);
    void *p = mmap((void *)start, end - start, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED_NOREPLACE,
                   -1, 0);
    if (p != (void *)start)
      return fprintf(stderr, "%s: cannot map 0x%lx\n", path, start), 0;
    memcpy((void *)ph[i].p_vaddr, file + ph[i].p_offset, ph[i].p_filesz);
    int writable = (ph[i].p_flags & PF_W) != 0;
    if (is_image && writable) {
      // Generated contents where the file has none, so the program's global pointers lead somewhere.
      uint64_t from = ph[i].p_vaddr + ph[i].p_filesz;
      for (uint64_t a = (from + 7) & ~7UL; a + 8 <= end; a += 8) {
        uint64_t w = word_at(a);
        memcpy((void *)a, &w, 8);
      }
    }
    int prot = PROT_READ | (writable ? PROT_WRITE : 0) | (!is_image && (ph[i].p_flags & PF_X) ? PROT_EXEC : 0);
    mprotect(p, end - start, prot);
    segments[*count] = (struct segment){ start, end, writable, NULL };
    if (writable) {
      segments[*count].pristine = malloc(end - start);
      memcpy(segments[*count].pristine, (void *)start, end - start);
    }
    if (is_image && (ph[i].p_flags & PF_X)) {
      *text_start = start;
      *text_end = end;
    }
    (*count)++;
  }
  munmap(file, st.st_size);
  close(fd);
  return 1;
}

// oracle_call(entry, regs, result): call entry with the argument registers set from regs.
// oracle_thunk: the target of named stubs (r11 holds the stub's name); it hands the argument registers to
// oracle_stub and returns its values.
__asm__(".text\n"
        ".globl oracle_call\n"
        "oracle_call:\n"
        "  push %rbp; mov %rsp, %rbp; push %rbx; push %r12; push %r13; push %r14; push %r15\n"
        "  push %rdx; mov %rsp, oracle_saved_rsp(%rip)\n"
        "  mov %rdi, %r11; mov %rsi, %r10\n"
        "  mov $0x300ffff0, %rsp\n"
        "  xor %ebx, %ebx; xor %ebp, %ebp; xor %r12d, %r12d; xor %r13d, %r13d; xor %r14d, %r14d; xor %r15d, %r15d\n"
        "  movq 48(%r10), %xmm0; movq 56(%r10), %xmm1; movq 64(%r10), %xmm2; movq 72(%r10), %xmm3\n"
        "  movq 80(%r10), %xmm4; movq 88(%r10), %xmm5; movq 96(%r10), %xmm6; movq 104(%r10), %xmm7\n"
        "  mov 0(%r10), %rdi; mov 8(%r10), %rsi; mov 16(%r10), %rdx; mov 24(%r10), %rcx\n"
        "  mov 32(%r10), %r8; mov 40(%r10), %r9; mov $8, %eax\n"
        "  call *%r11\n"
        "  mov oracle_saved_rsp(%rip), %rsp; pop %r10\n"
        "  mov %rsp, %rbp; add $40, %rbp\n"
        "  mov %rax, 0(%r10); mov %rdx, 8(%r10); movq %xmm0, 16(%r10); movq %xmm1, 24(%r10)\n"
        "  lea -40(%rbp), %rsp; pop %r15; pop %r14; pop %r13; pop %r12; pop %rbx; pop %rbp; ret\n"
        ".globl oracle_thunk\n"
        "oracle_thunk:\n"
        "  push %rbp; mov %rsp, %rbp; sub $160, %rsp; and $-16, %rsp\n"
        "  mov %rdi, 0(%rsp); mov %rsi, 8(%rsp); mov %rdx, 16(%rsp); mov %rcx, 24(%rsp); mov %r8, 32(%rsp)\n"
        "  mov %r9, 40(%rsp); movq %xmm0, 48(%rsp); movq %xmm1, 56(%rsp); movq %xmm2, 64(%rsp); movq %xmm3, 72(%rsp)\n"
        "  movq %xmm4, 80(%rsp); movq %xmm5, 88(%rsp); movq %xmm6, 96(%rsp); movq %xmm7, 104(%rsp); mov %rax, 112(%rsp)\n"
        "  mov %r11, %rdi; mov %rsp, %rsi; lea 120(%rsp), %rdx\n"
        "  call oracle_stub\n"
        "  mov 120(%rsp), %rax; mov 128(%rsp), %rdx; movq 136(%rsp), %xmm0; movq 144(%rsp), %xmm1\n"
        "  leave; ret\n");
void oracle_call(uint64_t entry, const struct regs *regs, struct result *result);
uint64_t oracle_saved_rsp;
void oracle_thunk(void);

int main(int argc, char **argv) {
  if (argc != 7)
    return fprintf(stderr, "usage: harness IMAGE VARIANT ENTRY ARGSPEC SEED COUNT\n"), 2;
  uint64_t entry = strtoull(argv[3], NULL, 0);
  const char *spec = argv[4];
  uint64_t first = strtoull(argv[5], NULL, 0), count = strtoull(argv[6], NULL, 0);
  seed = 0;  // the image's generated .bss contents use seed 0, the same for every case and variant
  if (!map_elf(argv[1], image, &image_count, 1, &image_text_start, &image_text_end) ||
      !map_elf(argv[2], variant, &variant_count, 0, NULL, NULL))
    return 1;
  // Named stubs jump through oracle_thunk_slot, a variant symbol at a fixed address given by oracle.py.
  const char *slot = getenv("ORACLE_THUNK_SLOT");
  if (slot)
    *(uint64_t *)strtoull(slot, NULL, 0) = (uint64_t)oracle_thunk;

  if (mmap((void *)STACK_BASE, STACK_SIZE, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED_NOREPLACE, -1,
           0) != (void *)STACK_BASE)
    return fprintf(stderr, "cannot map the stack\n"), 1;
  static char altstack[1 << 16];
  stack_t ss = { .ss_sp = altstack, .ss_size = sizeof(altstack) };
  sigaltstack(&ss, NULL);
  struct sigaction sa = { .sa_sigaction = handler, .sa_flags = SA_SIGINFO | SA_ONSTACK | SA_NODEFER };
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
  sigaction(SIGFPE, &sa, NULL);
  sigaction(SIGILL, &sa, NULL);
  sigaction(SIGALRM, &sa, NULL);

  for (uint64_t s = first; s < first + count; s++) {
    int fds[2];
    pipe(fds);
    pid_t pid = fork();
    if (pid == 0) {
      close(fds[0]);
      out_fd = fds[1];
      seed = s;
      struct regs regs = { 0 };
      int gp = 0, xmm = 0;
      for (const char *a = spec; *a; a++) {
        uint64_t h = mix(seed ^ mix(0xa000UL + (a - spec)));
        uint64_t value = *a == 'p' ? region_pointer(h)
                         : *a == 'b' ? h & 1
                         : *a == 'i' ? ((h >> 8) % 3 == 0 ? (h >> 16) : (h >> 16) % 64)
                         : *a == 'f' ? floats[h & 15]
                                     : doubles[h & 7];
        if (*a == 'f' || *a == 'd')
          regs.xmm[xmm++] = value;
        else
          regs.gp[gp++] = value;
      }
      alarm(2);
      struct result result;
      oracle_call(entry, &regs, &result);
      alarm(0);
      finish("return", 0, &result);
    }
    close(fds[1]);
    char buffer[1 << 16];
    ssize_t n;
    while ((n = read(fds[0], buffer, sizeof(buffer))) > 0)
      fwrite(buffer, 1, n, stdout);
    close(fds[0]);
    int status;
    waitpid(pid, &status, 0);
    if (!WIFEXITED(status) || WEXITSTATUS(status) != 0)
      printf("{\"seed\":%lu,\"outcome\":\"lost\",\"detail\":\"0x%x\",\"calls\":[],\"writes\":[]}\n", s, status);
    fflush(stdout);
  }
  return 0;
}
